/* Random internet events, the timed effects (buffs) they create, and text pools.
   Effect primitives are handled by js/systems/effects.js:
     {buff:key, mag?, duration?} timed effect (mag overrides its Attention multiplier)
     {chaos:n}                 move the Chaos meter now
     {stability:n}             move Stability now (losses scale with event severity)
     {att:seconds}             instant Attention (and the Money it earns)
     {money:seconds}           instant Money
     {loseMoney:frac, cap:sec} lose a share of Money, capped at `cap` seconds of income */
(function (Z) {
  'use strict';

  const own = (s, id) => s.buildings[id] || 0;
  // Sponsor events need that sponsor on the site (js/content/sponsors.js).
  const sponsor = id => s => !!(Z.SPONSOR && Z.SPONSOR[id] && Z.SPONSOR[id].active(s));
  const sponsorCount = s => (Z.SPONSORS ? Z.SPONSORS.filter(sp => sp.active(s)).length : 0);

  Z.TEXT = {
    topic: ['whether a hot dog is a sandwich', 'the correct way to hang toilet paper',
      'whether cereal is soup', 'how many holes a straw has', 'pineapple on pizza',
      'whether water is wet', 'how to pronounce GIF', 'tabs versus spaces',
      'whether the moon is overrated', 'if a pop-tart is a ravioli', 'the ideal number of pillows',
      'whether birds have knees', 'which way a fork should face in the dishwasher'],
    thing: ['a cat failing to jump onto a shelf', 'a man explaining spreadsheets to a goose',
      'a toddler reviewing restaurants', 'a sandwich being unwrapped very slowly',
      'a microwave beeping for eleven minutes', 'a dog wearing four tiny shoes',
      'a grandmother discovering the zoom button', 'a raccoon stealing an entire pizza'],
    celeb: ['a famous actor', 'a retired boy band member', 'a chef who yells a lot',
      'an astronaut', 'a reality TV villain', 'a tech billionaire', 'an extremely popular cat',
      'a news anchor, live on air'],
    meme: ['the Surprised Goose', 'Sad Keyboard Guy', 'This Is Fine But Worse',
      'Confused Accountant', 'the Overconfident Pigeon', 'Distracted Toaster'],
    minutes: ['47', '112', '63', '208', '19', '381'],
    millions: ['3', '12', '41', '7', '96'],
    year: ['2009', '2011', '2007', '2013'],
  };

  /* Buffs: timed modifiers. att/yield/control multiply, chaosAdd shifts the Chaos target,
     building+bMult boosts one building, noDrain stops Stability loss, chaosLock pins Chaos
     just under Tolerance. `viral` buffs track the Attention earned while active. */
  Z.BUFFS = {
    viral: { name: 'Viral Post', icon: '🔥', kind: 'good', duration: 25, att: 3, viral: true },
    celebrity: { name: 'Celebrity Boost', icon: '⭐', kind: 'good', duration: 20, att: 4 },
    argument: { name: 'Pointless Argument', icon: '💬', kind: 'good', duration: 45, att: 1.8, chaosAdd: 10 },
    biddingWar: { name: 'Advertiser Bidding War', icon: '💸', kind: 'good', duration: 45, yield: 2.5 },
    memeRevival: { name: 'Meme Renaissance', icon: '🖼️', kind: 'good', duration: 60, building: 'meme', bMult: 10 },
    leakBuzz: { name: 'Leak Buzz', icon: '📄', kind: 'good', duration: 30, att: 2.5 },
    fakeLeak: { name: 'Fake Leak', icon: '📄', kind: 'good', duration: 30, att: 3, chaosAdd: 15 },
    botUsers: { name: '"Real" Users', icon: '🤖', kind: 'good', duration: 60, att: 1.6, chaosAdd: 10 },
    blueMoney: { name: 'Blue Drink Money', icon: '🥤', kind: 'good', duration: 90, yield: 2 },
    trendjack: { name: 'Trendjacking', icon: '#️⃣', kind: 'good', duration: 40, att: 2 },
    drama: { name: 'Drama Spike', icon: '🍿', kind: 'good', duration: 30, att: 1.5 },
    squeeze: { name: 'Squeezed Users', icon: '🍋', kind: 'good', duration: 60, yield: 3 },
    apology: { name: 'Apology Tour', icon: '😔', kind: 'good', duration: 30, chaosAdd: -20 },
    tuning: { name: 'Algorithmic Tuning', icon: '🎛️', kind: 'good', duration: 60, chaosLock: true },
    lobbying: { name: 'Lobbying', icon: '💼', kind: 'good', duration: 60, noDrain: true },

    // Era mechanics (js/systems/eramech.js)
    flameWar: { name: 'Flame War', icon: '🔥', kind: 'good', duration: 120, att: 1.3, chaosAdd: 12, noChip: true },   // shown in the website window instead
    trendWave: { name: 'Riding a Trend', icon: '🌊', kind: 'good', duration: 30, att: 2.5 },
    aiHype: { name: 'AI Hype', icon: '🌈', kind: 'good', duration: 20, att: 3 },
    stockSurge: { name: 'Stock Surge', icon: '📈', kind: 'good', duration: 60, yield: 1.5 },
    botHelp: { name: 'Friendly Bots', icon: '🤖', kind: 'good', duration: 30, att: 1.5 },
    botWall: { name: 'Bot Firewall', icon: '🧱', kind: 'good', duration: 30, control: 1.3 },

    algoChange: { name: 'Algorithm Change', icon: '📉', kind: 'bad', duration: 60, att: 0.5 },
    advertiserGone: { name: 'Advertiser Exodus', icon: '🚪', kind: 'bad', duration: 60, yield: 0.7 },
    boycott: { name: 'Advertiser Boycott', icon: '🚪', kind: 'bad', duration: 30, yield: 0.5 },
    modScandal: { name: 'Moderation Scandal', icon: '🙈', kind: 'bad', duration: 60, control: 0.4 },
    cringe: { name: 'Cringe Meme', icon: '😬', kind: 'bad', duration: 120, building: 'meme', bMult: 0.25 },
    ddos: { name: 'DDoS Attack', icon: '🌊', kind: 'bad', duration: 30, att: 0.7 },
    cancelled: { name: 'Cancelled', icon: '🚫', kind: 'bad', duration: 60, att: 1.8, yield: 0.5 },
    cookieLaw: { name: 'Cookie Regulation', icon: '🍪', kind: 'bad', duration: 120, yield: 0.75 },
    banWave: { name: 'Ban Wave', icon: '🔨', kind: 'bad', duration: 30, att: 0.85 },
    sponsorPush: { name: 'Sponsor Push', icon: '🤝', kind: 'good', duration: 60, yield: 2 },
    sponsorSulk: { name: 'Sponsor Sulking', icon: '🤝', kind: 'bad', duration: 60, yield: 0.8 },
  };

  const E = def => def;

  Z.EVENTS = [
    /* ---------- Good ---------- */
    E({ id: 'viral', kind: 'good', icon: '🔥', weight: 7, title: 'A post went viral',
      text: ['Your post about {topic} went viral. Nobody can explain why.',
        'A screenshot of {site} is everywhere. It is cropped badly. Doesn\'t matter.',
        'Your post about {thing} has been shared {millions} million times.'],
      effects: [{ buff: 'viral', mag: g => 2.5 + g.s.res.chaos / 30 }] }),
    E({ id: 'celebrity', kind: 'good', icon: '⭐', weight: 5, title: 'A celebrity mentioned you',
      text: ['{celeb} just mentioned {site}. They might have meant a different site.'],
      req: s => s.run.attention >= 2000,
      choices: [
        { label: 'Repost it with "lmao"', stance: 'bold', effects: [{ buff: 'celebrity' }, { chaos: 15 }] },
        { label: 'Send a polite thank-you', stance: 'safe', effects: [{ money: 90 }, { stability: 5 }] },
      ] }),
    E({ id: 'video', kind: 'good', icon: '📹', weight: 6, title: 'A random video blew up',
      text: ['A video of {thing} got {millions} million views on {site}. Nobody knows who uploaded it.'],
      effects: [{ att: 120 }] }),
    E({ id: 'argument', kind: 'good', icon: '💬', weight: 7, title: 'Users are arguing',
      text: ['Users are arguing about {topic}. It has been going for {minutes} minutes.',
        'Congratulations. Someone argued in your comments for {minutes} minutes about {topic}.'],
      req: s => own(s, 'comments') >= 1,
      effects: [{ buff: 'argument' }, { chaos: 12 }] }),
    E({ id: 'biddingWar', kind: 'good', icon: '💸', weight: 5, title: 'Advertisers want your space',
      text: ['Two advertisers are fighting over your banner space. One of them sells left-handed scissors.'],
      req: s => own(s, 'adbanner') >= 3,
      effects: [{ buff: 'biddingWar' }] }),
    E({ id: 'memeRevival', kind: 'good', icon: '🖼️', weight: 4, title: 'Meme renaissance',
      text: ['{meme} is back. Ironically. Then sincerely. Then ironically again.'],
      req: s => own(s, 'meme') >= 5,
      effects: [{ buff: 'memeRevival' }] }),
    E({ id: 'wholesome', kind: 'good', icon: '🐶', title: 'A wholesome moment',
      weight: g => 2 + g.s.res.chaos / 15,
      text: ['Someone posted a picture of their dog. Everyone calmed down for a moment.',
        'A user thanked a stranger for help with their homework. The comments are confused but calm.'],
      req: s => s.res.chaos >= 20,
      effects: [{ chaos: -20 }, { stability: 10 }] }),
    E({ id: 'investor', kind: 'good', icon: '💼', weight: 4, title: 'An investor called',
      text: ['An investor called. They do not understand what you do either. They are in.'],
      req: s => s.run.attention >= 1e4,
      effects: [{ money: 180 }] }),
    E({ id: 'mom', kind: 'good', icon: '👩', title: 'Your first reader',
      weight: g => (g.s.run.attention < 5000 ? 12 : 0),
      text: ['Your article has been viewed 3 times. One of those views was your mother.',
        'Your mother shared {site} with her book club. Six new readers. Two are named Linda.'],
      effects: [{ att: 30 }] }),
    E({ id: 'leak', kind: 'good', icon: '📄', weight: 4, title: 'A feature "leaked"',
      text: ['Someone leaked an unreleased feature. It is a button that does nothing. Users love it.'],
      req: s => s.run.attention >= 5e4,
      effects: [{ buff: 'leakBuzz' }, { chaos: 10 }] }),
    E({ id: 'botSurge', kind: 'good', icon: '🤖', weight: 4, title: 'Suspicious new followers',
      text: ['A suspicious bot network started following you. 40,000 accounts. All named "user" plus eight digits.'],
      req: s => own(s, 'bots') >= 1 || s.run.attention >= 2e5,
      choices: [
        { label: 'Count them as real users', stance: 'bold', effects: [{ buff: 'botUsers' }, { chaos: 15 }, { stability: -10 }] },
        { label: 'Ban them all', stance: 'safe', effects: [{ buff: 'banWave' }, { chaos: -10 }] },
      ] }),
    E({ id: 'sponsorOffer', kind: 'good', icon: '🥤', weight: 4, title: 'A sponsor is interested',
      text: ['An energy drink brand wants to sponsor you. The drink is blue. Not the flavor. The color.'],
      req: s => s.run.money >= 1e5,
      choices: [
        { label: 'Take the blue money', stance: 'bold', effects: [{ buff: 'blueMoney' }, { chaos: 10 }] },
        { label: 'Politely decline', stance: 'safe', effects: [{ stability: 8 }, { money: 30 }] },
      ] }),
    E({ id: 'trendjack', kind: 'good', icon: '#️⃣', weight: 5, era: 2, title: 'You joined a trend',
      text: ['#{topic} is trending. You were not invited. You joined anyway.'],
      effects: [{ buff: 'trendjack' }] }),

    /* ---------- Bad ---------- */
    E({ id: 'server', kind: 'bad', icon: '💥', weight: 6, title: 'A server exploded',
      text: ['A server exploded. It was the important one.', 'A server caught fire. The fire department asked what a "server" is.'],
      calmText: 'A server caught fire. Your server survived. The fire did not.',
      req: s => own(s, 'closet') >= 1 || s.run.attention >= 3000,
      effects: g => (g.s.res.stability > 60 ? [{ stability: -10 }] : [{ stability: -25 }]) }),
    E({ id: 'algoChange', kind: 'bad', icon: '📉', weight: 5, title: 'Algorithm change',
      text: ['A platform changed its algorithm. Nobody knows why. Nobody ever will.'],
      req: s => s.run.attention >= 5000,
      effects: [{ buff: 'algoChange' }] }),
    E({ id: 'advertiser', kind: 'bad', icon: '🚪', weight: 5, title: 'An advertiser left',
      text: ['Your biggest advertiser left after reading the comment section.'],
      req: s => own(s, 'adbanner') >= 5,
      choices: [
        { label: 'Call them cowards publicly', stance: 'bold', effects: [{ buff: 'boycott' }, { buff: 'drama' }, { chaos: 20 }] },
        { label: 'Issue a calm statement', stance: 'safe', effects: [{ buff: 'advertiserGone' }, { chaos: -15 }] },
      ] }),
    E({ id: 'modScandal', kind: 'bad', icon: '🙈', weight: 4, title: 'Moderation scandal',
      text: ['Your moderation team has been replaced by three bots. Nobody noticed for a week.',
        'A moderator banned the entire country of Belgium. By accident. Allegedly.'],
      req: s => own(s, 'volunteer') >= 1,
      effects: [{ buff: 'modScandal' }] }),
    E({ id: 'cringe', kind: 'bad', icon: '😬', weight: 4, title: 'Meme is obsolete',
      text: ['{meme} is now cringe. The youth have moved on to something you will never understand.'],
      req: s => own(s, 'meme') >= 10,
      effects: [{ buff: 'cringe' }] }),
    E({ id: 'ddos', kind: 'bad', icon: '🌊', weight: 4, title: 'DDoS attack',
      text: ['Someone is DDoSing you. Probably a teenager. Probably bored.'],
      req: s => s.run.attention >= 1e4,
      effects: [{ stability: -15 }, { buff: 'ddos' }] }),
    E({ id: 'dataLeak', kind: 'bad', icon: '🔓', weight: 3, title: 'Database leaked',
      text: ['Your database was "shared" publicly. Lawyers have been notified. Lawyers are thrilled.'],
      req: s => s.run.money >= 1e5,
      effects: [{ loseMoney: 0.05, cap: 120 }, { chaos: 15 }] }),
    E({ id: 'cancelled', kind: 'bad', icon: '🚫', weight: g => g.s.res.chaos / 15, title: 'You have been cancelled',
      text: ['You have been cancelled for a post from {year}. The post was about soup.'],
      req: s => s.res.chaos >= 60,
      effects: [{ buff: 'cancelled' }, { chaos: 20 }] }),
    E({ id: 'cookieLaw', kind: 'bad', icon: '🍪', weight: 3, title: 'New cookie regulation',
      text: ['New regulation: every pixel now needs its own cookie consent banner.'],
      req: s => own(s, 'adbanner') >= 10,
      effects: [{ buff: 'cookieLaw' }] }),
    E({ id: 'outage', kind: 'bad', icon: '🔌', title: 'Hosting outage',
      weight: g => (g.s.res.stability < 40 ? 8 : 0),
      text: ['Your hosting provider is "investigating elevated error rates". It is a fire.'],
      effects: [{ stability: -20 }] }),
    E({ id: 'raid', kind: 'bad', icon: '🏴', weight: 4, title: 'Comment section raid',
      text: ['A rival forum is raiding your comment section. They brought memes. Bad ones.'],
      req: s => own(s, 'comments') >= 5,
      effects: [{ chaos: 25 }, { stability: -10 }, { att: 30 }] }),
    E({ id: 'hallucination', kind: 'bad', icon: '🌈', weight: 4, era: 5, title: 'Your AI hallucinated',
      text: ['Your AI published an article claiming the Moon is a franchise. It is your best performing article.'],
      effects: [{ chaos: 20 }, { att: 60 }] }),
    E({ id: 'shareholders', kind: 'bad', icon: '📊', weight: 5, era: 6, title: 'Shareholders demand growth',
      text: ['Shareholders demand growth. Any growth. Right now. Ideally yesterday.'],
      choices: [
        { label: 'Squeeze the users', stance: 'bold', effects: [{ buff: 'squeeze' }, { stability: -20 }] },
        { label: 'Promise "synergy"', stance: 'safe', effects: [{ money: 120 }] },
      ] }),

    /* ---------- Sponsors (only while that brand sponsors the site) ---------- */
    E({ id: 'voltRecall', kind: 'bad', icon: '⚡', weight: 3, title: 'BLU VOLT recall',
      text: ['BLU VOLT is recalling a batch of cans. Customers report their tongues are now permanently blue. They want {site} to say something.'],
      req: sponsor('volt'),
      choices: [
        { label: 'Post “blue is a lifestyle”', stance: 'bold', effects: [{ buff: 'drama' }, { chaos: 15 }, { money: 45 }] },
        { label: 'Pause the sponsorship for a day', stance: 'safe', effects: [{ buff: 'sponsorSulk' }, { chaos: -10 }, { stability: 8 }] },
      ] }),
    E({ id: 'crumbLeak', kind: 'bad', icon: '🍪', weight: 3, title: 'CrumbTrack tracking scandal',
      text: ['CrumbTrack’s cookies were caught tracking what users dream about. Regulators want to know which site showed the most cookie banners. It was {site}.'],
      req: sponsor('crumb'),
      choices: [
        { label: 'Add even more cookie banners', stance: 'bold', effects: [{ buff: 'biddingWar' }, { chaos: 15 }, { stability: -10 }] },
        { label: 'Switch the tracking off', stance: 'safe', effects: [{ buff: 'cookieLaw' }, { stability: 10 }] },
      ] }),
    E({ id: 'sauceFeud', kind: 'good', icon: '🌶️', weight: 3, title: 'Hot Take Sauce started a feud',
      text: ['Hot Take Sauce posted that mild salsa is "for cowards". The salsa community is furious, and they are in your comments.'],
      req: sponsor('sauce'),
      choices: [
        { label: 'Agree, loudly', stance: 'bold', effects: [{ buff: 'argument' }, { chaos: 15 }] },
        { label: 'Stay neutral and eat a cracker', stance: 'safe', effects: [{ money: 45 }] },
      ] }),
    E({ id: 'reelzWedding', kind: 'bad', icon: '▶️', weight: 3, title: 'Reelz+ crashed a wedding',
      text: ['A Reelz+ ad autoplayed during a wedding livestream on {site}. At full volume. During the vows.'],
      req: sponsor('reelz'),
      choices: [
        { label: 'Call it “engagement”', stance: 'bold', effects: [{ buff: 'leakBuzz' }, { chaos: 15 }, { stability: -8 }] },
        { label: 'Refund the happy couple', stance: 'safe', effects: [{ loseMoney: 0.03, cap: 60 }, { stability: 10 }] },
      ] }),
    E({ id: 'snoozeDemand', kind: 'good', icon: '🛏️', weight: 3, title: 'SnoozeCloud has a request',
      text: ['SnoozeCloud wants every post on {site} to mention mattresses at least once. Including the obituaries.'],
      req: sponsor('snooze'),
      choices: [
        { label: 'Mattress everything', stance: 'bold', effects: [{ buff: 'sponsorPush' }, { chaos: 10 }] },
        { label: 'Offer every other post', stance: 'safe', effects: [{ money: 60 }] },
      ] }),
    E({ id: 'dealGlitch', kind: 'bad', icon: '🔗', weight: 3, title: 'DealHoarder code glitch',
      text: ['DealHoarder’s code CHAOS is giving 100% off by mistake. Your users have ordered 40,000 air fryers.'],
      req: sponsor('deal'),
      choices: [
        { label: 'Say nothing and enjoy the traffic', stance: 'bold', effects: [{ att: 90 }, { chaos: 20 }, { stability: -10 }] },
        { label: 'Warn your users', stance: 'safe', effects: [{ stability: 10 }, { money: 30 }] },
      ] }),
    E({ id: 'sponsorParty', kind: 'good', icon: '🤝', weight: 3, title: 'Your sponsors are thrilled',
      text: ['Your sponsors loved this week’s numbers. They sent a fruit basket and a slightly larger check.'],
      req: s => sponsorCount(s) >= 2,
      effects: [{ buff: 'sponsorPush' }] }),
  ];
  Z.EV = Z.util.byId(Z.EVENTS);
})(window.ICHAOS = window.ICHAOS || {});
