/* Clout perks (permanent, bought with Clout from Internet Eras) and player actions. */
(function (Z) {
  'use strict';

  /* cost(level) = ceil(cost × growth^level). Effects apply once per level. */
  Z.PERKS = [
    { id: 'brand', name: 'Brand Recognition', icon: '⭐', cost: 1, growth: 1.6, max: 200,
      desc: '+25% Attention per level.', effects: [{ t: 'attBonus', v: 0.25 }] },
    { id: 'muscle', name: 'Muscle Memory', icon: '💪', cost: 1, growth: 2, max: 6,
      desc: 'Click power ×2 per level.', effects: [{ t: 'clickMult', x: 2 }] },
    { id: 'seed', name: 'Seed Funding', icon: '💵', cost: 2, growth: 3, max: 5,
      desc: 'Start each era with $1K, then ×30 per extra level.',
      apply(m, lvl) { m.startMoney = 1000 * Math.pow(30, lvl - 1); } },
    { id: 'legacy', name: 'Legacy Content', icon: '📚', cost: 2, growth: 2.2, max: 5,
      desc: 'Start each era with 10 Blog Posts, 5 Meme Pages and 1 Closet Server per level.',
      apply(m, lvl) { m.startBuildings = { blog: 10 * lvl, meme: 5 * lvl, closet: lvl }; } },
    { id: 'redundancy', name: 'Redundant Servers', icon: '🧯', cost: 3, growth: 1.8, max: 5,
      desc: '+4 Chaos Tolerance per level.', effects: [{ t: 'tolerance', v: 4 }] },
    { id: 'chaostheory', name: 'Chaos Theory', icon: '🌀', cost: 3, growth: 2, max: 6,
      desc: 'Chaos boosts Attention +25% more (at 100% Chaos) per level.', effects: [{ t: 'chaosAtt', v: 0.25 }] },
    { id: 'veterans', name: 'Veteran Moderators', icon: '🎖️', cost: 2, growth: 1.7, max: 10,
      desc: '+30% Control per level.', effects: [{ t: 'controlMult', x: 1.3 }] },
    { id: 'insurance', name: 'Meltdown Insurance', icon: '🧾', cost: 3, growth: 2, max: 3,
      desc: 'Meltdowns are 25% shorter and restart with +10 Stability per level.',
      effects: [{ t: 'meltdownMult', x: 0.75 }, { t: 'meltdownStability', v: 10 }] },
    { id: 'nightshift', name: 'Night Shift', icon: '🌙', cost: 2, growth: 2, max: 4,
      desc: 'Offline progress: +4 hours of cap and +10% efficiency per level.',
      effects: [{ t: 'offlineCap', v: 4 }, { t: 'offlineEff', v: 0.1 }] },
    { id: 'luck', name: 'Algorithmic Luck', icon: '🍀', cost: 3, growth: 1.8, max: 5,
      desc: 'Good events are 20% more likely per level.', effects: [{ t: 'goodEvents', x: 1.2 }] },
    { id: 'clickfarm', name: 'Click Farm', icon: '🧑‍🌾', cost: 2, growth: 1.7, max: 10,
      desc: '+3 automatic clicks per second per level.', effects: [{ t: 'autoClick', v: 3 }] },
    { id: 'institutional', name: 'Institutional Memory', icon: '🗂️', cost: 6, growth: 1, max: 1,
      desc: 'Keep the Intern (2 auto-clicks/s) and SRE auto-Hotfix from the start of every era.',
      effects: [{ t: 'autoClick', v: 2 }, { t: 'autoHotfix' }] },
    { id: 'unhinged', name: 'Born Unhinged', icon: '🦝', cost: 5, growth: 1, max: 1,
      desc: 'The Unhinged policy is available from the start of every era.',
      effects: [{ t: 'policy', id: 'unhinged' }] },
    { id: 'growth', name: 'Growth Hacker', icon: '📊', cost: 5, growth: 1, max: 1,
      desc: 'Unlocks the Auto-Buyer. It buys the cheapest item in the categories you pick.',
      effects: [{ t: 'autobuy' }] },
    { id: 'growth2', name: 'Growth Hacker Pro', icon: '🚀', cost: 10, growth: 2.5, max: 3,
      desc: 'The Auto-Buyer acts twice as often per level.', req: s => (s.perks.growth || 0) > 0,
      effects: [{ t: 'autobuySpeed', v: 1 }] },
    { id: 'risk', name: 'Risk Manager', icon: '🎚️', cost: 8, growth: 1, max: 1,
      desc: 'Unlocks Auto-Policy. It nudges your Editorial Policy to keep Chaos near Tolerance.',
      effects: [{ t: 'riskManager' }] },
    { id: 'pr', name: 'PR Autopilot', icon: '🎙️', cost: 4, growth: 1, max: 1,
      desc: 'Unlocks automatic answers to choice events, using the stance you pick.',
      effects: [{ t: 'prAutopilot' }] },
    { id: 'scheduler', name: 'Content Scheduler', icon: '🗓️', cost: 12, growth: 1, max: 1,
      desc: 'Unlocks Auto-Actions: Stir the Pot and Apology Video fire by themselves when useful.',
      effects: [{ t: 'scheduler' }] },
  ];
  Z.PERK = Z.util.byId(Z.PERKS);

  /* Actions: active abilities with cooldowns. `run(g)` returns effects for js/systems/effects.js
     or performs custom logic. */
  Z.ACTIONS = [
    { id: 'stir', name: 'Stir the Pot', icon: '🥄', cooldown: 40,
      desc: 'Post a deliberately controversial take.',
      unlock: g => (g.s.buildings.comments || 0) >= 1,
      effects: [{ chaos: 25 }, { att: 15 }] },
    { id: 'hotfix', name: 'Hotfix', icon: '🩹', cooldown: 60,
      desc: 'Push untested code straight to production. During a meltdown it cuts downtime instead.',
      unlock: g => (g.s.buildings.closet || 0) >= 1 || g.m.autoHotfix,
      effects: g => [{ stability: 20 + g.m.hotfixPower }] },
    { id: 'apology', name: 'Apology Video', icon: '😔', cooldown: 150,
      desc: 'Sit in front of a gray wall and look at the floor.',
      unlock: g => !!g.m.actions.apology,
      effects: [{ chaos: -40 }, { stability: 5 }, { buff: 'apology' }] },
    { id: 'leak', name: 'Fake Leak', icon: '📄', cooldown: 240, era: 3,
      desc: '"Accidentally" leak a feature that does not exist.',
      unlock: g => g.s.era >= 3,
      effects: [{ buff: 'fakeLeak' }] },
    { id: 'tune', name: 'Algorithmic Tuning', icon: '🎛️', cooldown: 300, era: 4,
      desc: 'Pin Chaos just under your Tolerance: maximum growth, no drain.',
      unlock: g => g.s.era >= 4,
      effects: [{ buff: 'tuning' }] },
    { id: 'hallucinate', name: 'Hallucinate Content', icon: '🌈', cooldown: 600, era: 5,
      desc: 'Your AI invents five minutes of Attention out of nothing.',
      unlock: g => g.s.era >= 5,
      effects: [{ att: 300 }, { chaos: 30 }] },
    { id: 'lobby', name: 'Lobbying', icon: '💼', cooldown: 480, era: 6,
      desc: 'Stability cannot drain for a while. Politicians have been informed.',
      unlock: g => g.s.era >= 6,
      effects: [{ buff: 'lobbying' }] },
  ];
  Z.ACT = Z.util.byId(Z.ACTIONS);
})(window.ICHAOS = window.ICHAOS || {});
